create table event_category (
category_id bigint generated by default as identity,
 category_name varchar(255) not null,
 is_deleted boolean, primary key (category_id));

 insert into event_category  values (1, 'Party', false);
 insert into event_category values (2, 'Wedding', false);
 insert into event_category values (3, 'Funeral', false);
